version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: inventory-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: inventory
    volumes:
      - mongodb_data:/data/db
    networks:
      - inventory-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/inventory --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: inventory-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis123
    volumes:
      - redis_data:/data
    networks:
      - inventory-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  inventory-network:
    driver: bridge
